### ISSUE TITLE
Calling twice completion

### ISSUE THREAD

**Issue by josete89** [objcio/s01e47-testable-view-models-at-kickstarter#1]
func stripeCreatedToken(token: STPToken?, error: Error?, completion: @escaping (PKPaymentAuthorizationStatus) -> Void) {
        if let token = token {
            Webservice.shared.processToken(token: token, product: self.product, callback: { success in
                if success {
                    self.state.statusLabelText = "Thank you"
                    completion(.success)
                } else {
                    self.state.statusLabelText = "Something went wrong."
                    completion(.failure)
                }
            })
            **completion(.success)** -> **is that correct?**
        } else if let error = error {
            self.state.statusLabelText = "Stripe error \(error)..."
            completion(.failure)
        } else {
            fatalError()
        }
    }

**Comment by floriankugler** [comment]
@josete89 Yes, that's a mistake – we missed to fix it in the sample code. I think the video/transcript should already have the correction.

Thanks for the feedback!
